/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-interface-protection.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.rfc8561.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-interface-protection.yang */
public class ietfInterfaceProtection extends ConfNamespace {
    public static final int hash = 1408671170;
    public int hash() {
        return ietfInterfaceProtection.hash;
    }

    public static final String id = "_rfc8561-nc-1.0:rfc8561-nc-1.0#urn:ietf:params:xml:ns:yang:ietf-interface-protection";
    public String id() {
        return ietfInterfaceProtection.id;
    }

    public static final String uri = "_rfc8561-nc-1.0:rfc8561-nc-1.0#urn:ietf:params:xml:ns:yang:ietf-interface-protection";
    public String uri() {
        return ietfInterfaceProtection.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfInterfaceProtection.uri);
    }

    public static final String prefix = "ifprot";
    public String prefix() {
        return ietfInterfaceProtection.prefix;
    }

    public ietfInterfaceProtection() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _unprotected = 123351716;
    public static final String _unprotected_ = "unprotected";
    public static final int    _protection_states = 1469229817;
    public static final String _protection_states_ = "protection-states";
    public static final int    _protection_architecture_type = 1209944337;
    public static final String _protection_architecture_type_ = "protection-architecture-type";
    public static final int    _unable_to_protect = 1488978338;
    public static final String _unable_to_protect_ = "unable-to-protect";
    public static final int    _one_plus_one_type = 121296504;
    public static final String _one_plus_one_type_ = "one-plus-one-type";
    public static final int    _one_to_n_type = 1902034531;
    public static final String _one_to_n_type_ = "one-to-n-type";
    public static final int    _protected = 115064703;
    public static final String _protected_ = "protected";
}
